version: "3"

services:
  postgres-database:
    build:
      context: ./database/
      dockerfile: Containerfile
    image: pre-initialized-postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data:Z

        #  fastapi:
        #    build:
        #      context: ./server/
        #      dockerfile: Containerfile 
        #    image: fast-api
        #    ports:
        #      - 5000:5000
        #    command: uvicorn --host 0.0.0.0 
