version: "3"

services:
  database:
    container_name: postgres_database
    build:
      context: ./database/
      dockerfile: ./Containerfile
    image: initialized_postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data:Z
